plugins {
    id 'com.android.application'
}
def bundleName
def variantType
def getVersion() {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('version.properties').newDataInputStream())
    return properties.getProperty("VERSION_CODE")
}
//修改输出APK包名
//android.applicationVariants.all { variant ->
//    variantType = variant.buildType.name
//    variant.outputs.each { output ->
//        variant.outputs.all {
//            bundleName = "AirQuality" + "-" + getVersion()
//            outputFileName = bundleName + '.apk'
//        }
//    }
//}
android {
    compileSdk 34

    defaultConfig {
        applicationId "com.ttu.airquality"
        minSdk 23
        targetSdk 34
        versionCode 6
        versionName "1.5"
//        buildConfigField "String", "VERSION", "\"" + getVersion() + "\""
        setProperty("archivesBaseName", "${applicationId}-v${versionName}")
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}